[package]
name = "bridge-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
bridge-engine.workspace = true
tauri.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]

[lints]
workspace = true
